import type {Metadata} from "next";
import {Crete_Round, Inter, Work_Sans} from "next/font/google";
import "./globals.css";
import {ChildProps} from "@/types";
import {ThemeProvider} from "@/components/providers/theme-provider";
import { SessionProvider } from "next-auth/react";
import { auth } from '@/auth'

const inter = Inter({subsets: ["latin"]});
const creteRound = Crete_Round({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-creteRound",
})
const workSans = Work_Sans({
    weight: ["500", "600"],
    subsets: ["latin"],
    variable: "--font-workSans",
})

export const metadata: Metadata = {
    title: "Next Blog",
    description: "Generated by Bobur",
};

export default async function RootLayout({children}: ChildProps) {
    const session = await auth()

    return (
        <SessionProvider session={session}>
            <html lang="en" suppressHydrationWarning>
            <body className={`${creteRound.variable} ${workSans.variable} overflow-x-hidden`}>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                {children}
            </ThemeProvider>
            </body>
            </html>
        </SessionProvider>
    );
}
